---
title: "HW1-Q2"
author: "Zhaoqi Li"
date: "2023/1/25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(combinat)
```
### Q2.i

```{r}
y1<-c(18.5,20.3,18.5,14.1,49.2,31.2,25.1)
y2<-c(16.4,13.3,23.3,15.6,14.2,16,10.9,9.3,12.7)
population <- c(y1,y2)
sample<- c(rep(1,times=length(y1)),rep(2, times=length(y2)) )
observed<- mean(y1) - mean(y2)
n<- length(population)
n1<- length(y1)
N <- choose(n, n1)
TS <- numeric(N) 
index <- combn(1:n,n1)
for (i in 1:N)
{
TS[i] <- mean(population[index[,i]]) - mean(population[-index[,i]])
}
tbar <- mean(TS)
pval <- sum(abs(TS - tbar) >= abs(observed - tbar))/N
pval
```

### Q2.ii

```{r}
N <- 6000 
TS <- numeric(N)
set.seed(407)
for (i in 1:N) {
index <- sample(length(population),size = length(y1),replace = FALSE)
TS[i] <- mean(population[index]) - mean(population[-index])
}
observed <- mean(y1) - mean(y2)
tbar <- mean(TS)
phatval <- (sum( abs(TS -tbar) >= abs(observed - tbar))+1)/(N+1)
phatval
```

